### ISSUE TITLE
No module _winreg

### ISSUE THREAD

**Issue by jmindek** [kislyuk/signxml#11]
Running cherrypy web app on Ubuntu 14.04.
`from signxml import xmldsig`
causes the following error when I start up my app:
> [08/May/2015:14:56:06] ENGINE Bus STARTED
> [08/May/2015:14:56:07] ENGINE Error in background task thread function <bound method > Autoreloader.run of <cherrypy.process.plugins.Autoreloader object at 0x7f3f498477d0>>.
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/plugins.py", line 500, in run
>     self.function(*self.args, **self.kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/plugins.py", line 632, in run
>     for filename in self.sysfiles() | self.files:
>   File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/plugins.py", line 621, in sysfiles
>     f = getattr(m, '__file__', None)
>   File "/usr/local/lib/python2.7/dist-packages/eight/utils.py", line 41, in __getattr__
>     self._module = __import__(self._name)
> ImportError: No module named _winreg`

**Comment by ldnunes** [comment]
Hi @jmindek, can you provide a gist using those libraries where this exception happen?

**Comment by jmindek** [comment]
Sure.
Here you go:
https://gist.github.com/jmindek/c04ce660d03b2f1b8562 <https://gist.github.com/jmindek/c04ce660d03b2f1b8562>

Thanks,
Jerry

**Comment by kislyuk** [comment]
A dependency of signxml, eight, provides a module name remapping system that lazy-loads modules that were renamed between Python 2 and 3. CherryPy's autoreloader plugin seems to interact poorly with this system by trying to load every single module listed in sys.modules (not something that should normally be done), and finding a module in the remapping that actually can't be loaded on Linux.

I'm thinking of working around this, but my take on this is that the bug is actually in CherryPy (it shouldn't try to load all modules in sys.modules in its autoreloader).

**Comment by kislyuk** [comment]
I have updated eight to version 0.3.1, including a bugfix which should eliminate this problem. Please update it and try again.

**Comment by jmindek** [comment]
Thanks, issue resolved!
