### ISSUE TITLE
Wrong Signature Value

### ISSUE THREAD

**Issue by pancha55555** [kislyuk/signxml#44]
Hello.

I´m having a little problem with a xml digital signature. I have a working example in php and when I generate the same digital signature it gives me a different signature value. everything is the same except for the signature value. could you help me to find out what I´m missing? i attached what I´m using

[signXML.zip](https://github.com/kislyuk/signxml/files/148514/signXML.zip)

**Comment by klondi** [comment]
@pancha55555 The DigestValue is the same so the XML being signed is the same, actually (except for the unknown CA issue) all 3 of them verify with xmlsec1 too on https://www.aleksey.com/xmlsec/xmldsig-verifier.html

If the issue is the certificate data you are missing you'll have to add it yourself I suspect.

**Comment by pancha55555** [comment]
@klondi Now that I think about It, you are totally right. The SignatureValue doesn´t have to be the same in other languages (at least in my case). I can´t believe I was so stupid cause I din´t realize. I apologize for my error and really appreciate your help. thank you very much!!.

P.S. I was trying to get the same SignatureValue in php and python so I can send the xml to a web service, but I hadn´t done the test of sending the python xml, now that I did I see there´s nothing wrong. Again, I apologize.
